---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: "test/integration/data_bags"

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: restart
    run_list:
      - recipe[databag_restart_model::restart]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:

  - name: notify
    run_list:
      - recipe[databag_restart_model::notify]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
